service: shopify-custom-price
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    SHOPIFY_ACCESS_TOKEN: ${env:SHOPIFY_ACCESS_TOKEN}
    SHOPIFY_STORE_URL: ${env:SHOPIFY_STORE_URL}

custom:
  corsConfig: &corsConfig
    origin: '*'
    headers:
      - Content-Type
      - X-Amz-Date
      - Authorization
      - X-Api-Key
      - X-Amz-Security-Token
      - X-Amz-User-Agent

functions:
  createSizeVariant:
    handler: handler.createSizeVariant
    timeout: 300
    events:
      - http:
          path: create-size-variant
          method: post
          cors: *corsConfig
  deleteSizeVariant:
    handler: handler.deleteSizeVariant
    timeout: 300
    events:
      - http:
          path: delete-size-variant
          method: post
          cors: *corsConfig
  orderComplete:
    handler: handler.orderComplete
    timeout: 300
    events:
      - http:
          path: order-complete
          method: post
          cors: *corsConfig
  deleteOldVariants:
    handler: handler.deleteOldVariants
    timeout: 300
    events:
      - schedule:
          rate: rate(1 day)
      - http:
          path: delete-old-variants
          method: post
          cors: *corsConfig

plugins:
  - serverless-offline
  - serverless-dotenv-plugin